### ISSUE TITLE
Using luastatic to build for Windows

### ISSUE THREAD

**Issue by ers35** [PixetBits/ghost#1]
I see there is a question about building for Windows. Have you seen this example? http://lua.space/tools/build-a-standalone-executable

You should be able to cross compile for Windows on GNU/Linux like this:
`CC=x86_64-w64-mingw32-gcc luastatic ghost.lua leaf.lua liblua.a -Ilua-5.3.5/src`

You'll have to build Lua for Windows as shown in the linked example.

Let me know if there are any questions.

**Comment by PixetBits** [comment]
Thank you very much. I will try as soon as possible

**Comment by PixetBits** [comment]
Worked pretty well (after some broken packages and timeshifts hehe) Thanks
